const { PlantProfile } = require('../models');

const plantData = [
  {
    name: 'Lettuce',
    scientificName: 'Lactuca sativa',
    category: 'leafy',
    difficulty: 'easy',
    growthTime: 30,
    optimalPhMin: 5.5,
    optimalPhMax: 6.5,
    optimalTdsMin: 400,
    optimalTdsMax: 800,
    optimalWaterTempMin: 16.0,
    optimalWaterTempMax: 20.0,
    optimalAirTempMin: 18.0,
    optimalAirTempMax: 22.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '12-16 hours daily, moderate intensity',
    description: 'Fast-growing and ideal for beginners. Grows well in hydroponic systems with minimal nutrients.',
    image: 'https://example.com/lettuce.jpg',
    maintenanceLevel: 'low',
    notes: 'Use lower nutrient strength. Harvest outer leaves as needed for continuous production.'
  },
  {
    name: 'Spinach',
    scientificName: 'Spinacia oleracea',
    category: 'leafy',
    difficulty: 'moderate',
    growthTime: 35,
    optimalPhMin: 6.0,
    optimalPhMax: 7.0,
    optimalTdsMin: 600,
    optimalTdsMax: 1000,
    optimalWaterTempMin: 15.0,
    optimalWaterTempMax: 18.0,
    optimalAirTempMin: 15.0,
    optimalAirTempMax: 20.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '12-14 hours daily, moderate intensity',
    description: 'Cool-weather crop that prefers lower temperatures. Rich in nutrients and grows quickly.',
    image: 'https://example.com/spinach.jpg',
    maintenanceLevel: 'low',
    notes: 'Sensitive to high temperatures. Provide cooler conditions for best results.'
  },
  {
    name: 'Basil',
    scientificName: 'Ocimum basilicum',
    category: 'herb',
    difficulty: 'moderate',
    growthTime: 45,
    optimalPhMin: 5.5,
    optimalPhMax: 6.5,
    optimalTdsMin: 800,
    optimalTdsMax: 1200,
    optimalWaterTempMin: 18.0,
    optimalWaterTempMax: 22.0,
    optimalAirTempMin: 20.0,
    optimalAirTempMax: 28.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '12-16 hours daily, high intensity',
    description: 'Aromatic herb that grows well in hydroponic systems. Requires proper nutrition for flavor.',
    image: 'https://example.com/basil.jpg',
    maintenanceLevel: 'medium',
    notes: 'Pinch flowers to encourage leaf growth. Prune regularly for bushy plants.'
  },
  {
    name: 'Parsley',
    scientificName: 'Petroselinum crispum',
    category: 'herb',
    difficulty: 'easy',
    growthTime: 75,
    optimalPhMin: 5.5,
    optimalPhMax: 6.5,
    optimalTdsMin: 600,
    optimalTdsMax: 1000,
    optimalWaterTempMin: 18.0,
    optimalWaterTempMax: 22.0,
    optimalAirTempMin: 18.0,
    optimalAirTempMax: 22.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '10-12 hours daily, moderate intensity',
    description: 'Hardy herb that tolerates various growing conditions. Slow growing but very productive.',
    image: 'https://example.com/parsley.jpg',
    maintenanceLevel: 'low',
    notes: 'Can tolerate lower light conditions. Slow growing but very productive once established.'
  },
  {
    name: 'Mint',
    scientificName: 'Mentha spicata',
    category: 'herb',
    difficulty: 'easy',
    growthTime: 60,
    optimalPhMin: 5.5,
    optimalPhMax: 6.5,
    optimalTdsMin: 600,
    optimalTdsMax: 1000,
    optimalWaterTempMin: 16.0,
    optimalWaterTempMax: 21.0,
    optimalAirTempMin: 15.0,
    optimalAirTempMax: 25.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '8-12 hours daily, moderate intensity',
    description: 'Fast-growing herb that requires containment to prevent overgrowth. Refreshes frequently.',
    image: 'https://example.com/mint.jpg',
    maintenanceLevel: 'low',
    notes: 'Can be invasive. Harvest regularly to maintain plant health and flavor.'
  },
  {
    name: 'Kale',
    scientificName: 'Brassica oleracea',
    category: 'leafy',
    difficulty: 'moderate',
    growthTime: 55,
    optimalPhMin: 6.0,
    optimalPhMax: 7.0,
    optimalTdsMin: 800,
    optimalTdsMax: 1200,
    optimalWaterTempMin: 15.0,
    optimalWaterTempMax: 20.0,
    optimalAirTempMin: 15.0,
    optimalAirTempMax: 25.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '12-16 hours daily, high intensity',
    description: 'Nutrient-dense leafy green that benefits from cooler temperatures. Slow bolting.',
    image: 'https://example.com/kale.jpg',
    maintenanceLevel: 'medium',
    notes: 'Prefers cooler conditions. Harvest outer leaves to encourage continuous growth.'
  },
  {
    name: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    category: 'fruit',
    difficulty: 'difficult',
    growthTime: 85,
    optimalPhMin: 5.8,
    optimalPhMax: 6.8,
    optimalTdsMin: 1200,
    optimalTdsMax: 2000,
    optimalWaterTempMin: 18.0,
    optimalWaterTempMax: 22.0,
    optimalAirTempMin: 20.0,
    optimalAirTempMax: 28.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '14-16 hours daily, high intensity',
    description: 'Popular fruiting plant that requires careful attention and support structures.',
    image: 'https://example.com/tomato.jpg',
    maintenanceLevel: 'high',
    notes: 'Requires support structures. Prune suckers regularly and maintain consistent watering.'
  },
  {
    name: 'Cucumber',
    scientificName: 'Cucumis sativus',
    category: 'fruit',
    difficulty: 'difficult',
    growthTime: 50,
    optimalPhMin: 5.5,
    optimalPhMax: 6.5,
    optimalTdsMin: 1000,
    optimalTdsMax: 1500,
    optimalWaterTempMin: 18.0,
    optimalWaterTempMax: 22.0,
    optimalAirTempMin: 22.0,
    optimalAirTempMax: 28.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '14-16 hours daily, high intensity',
    description: 'Fast-growing vining plant that requires support structures and consistent conditions.',
    image: 'https://example.com/cucumber.jpg',
    maintenanceLevel: 'high',
    notes: 'Requires trellising and consistent environmental conditions. Harvest frequently.'
  },
  {
    name: 'Bell Pepper',
    scientificName: 'Capsicum annuum',
    category: 'fruit',
    difficulty: 'difficult',
    growthTime: 90,
    optimalPhMin: 5.5,
    optimalPhMax: 6.5,
    optimalTdsMin: 1200,
    optimalTdsMax: 1800,
    optimalWaterTempMin: 18.0,
    optimalWaterTempMax: 22.0,
    optimalAirTempMin: 22.0,
    optimalAirTempMax: 28.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '14-16 hours daily, high intensity',
    description: 'Colorful fruiting plants that require warm temperatures and stable conditions.',
    image: 'https://example.com/bell_pepper.jpg',
    maintenanceLevel: 'high',
    notes: 'Require warmer temperatures than other plants. Support heavy fruit loads.'
  },
  {
    name: 'Strawberry',
    scientificName: 'Fragaria × ananassa',
    category: 'fruit',
    difficulty: 'difficult',
    growthTime: 90,
    optimalPhMin: 5.5,
    optimalPhMax: 6.5,
    optimalTdsMin: 800,
    optimalTdsMax: 1200,
    optimalWaterTempMin: 15.0,
    optimalWaterTempMax: 20.0,
    optimalAirTempMin: 15.0,
    optimalAirTempMax: 25.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '10-12 hours daily, moderate to high intensity',
    description: 'Delicious fruits that can be grown in hydroponic systems with proper care.',
    image: 'https://example.com/strawberry.jpg',
    maintenanceLevel: 'high',
    notes: 'Requires specific day-length conditions. Remove runners for fruit production.'
  },
  {
    name: 'Cherry Tomato',
    scientificName: 'Solanum lycopersicum',
    category: 'fruit',
    difficulty: 'difficult',
    growthTime: 70,
    optimalPhMin: 5.8,
    optimalPhMax: 6.8,
    optimalTdsMin: 1000,
    optimalTdsMax: 1800,
    optimalWaterTempMin: 18.0,
    optimalWaterTempMax: 22.0,
    optimalAirTempMin: 20.0,
    optimalAirTempMax: 28.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '14-16 hours daily, high intensity',
    description: 'Smaller version of tomatoes, perfect for hydroponic growing with sweeter flavor.',
    image: 'https://example.com/cherry_tomato.jpg',
    maintenanceLevel: 'high',
    notes: 'Similar care to regular tomatoes but with sweeter flavor. Prune regularly.'
  },
  {
    name: 'Arugula',
    scientificName: 'Eruca sativa',
    category: 'leafy',
    difficulty: 'easy',
    growthTime: 25,
    optimalPhMin: 6.0,
    optimalPhMax: 7.0,
    optimalTdsMin: 400,
    optimalTdsMax: 800,
    optimalWaterTempMin: 15.0,
    optimalWaterTempMax: 20.0,
    optimalAirTempMin: 15.0,
    optimalAirTempMax: 20.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '8-10 hours daily, moderate intensity',
    description: 'Peppery green that grows quickly. Perfect for fast harvests with distinctive flavor.',
    image: 'https://example.com/arugula.jpg',
    maintenanceLevel: 'low',
    notes: 'Fast growing and bolt-prone. Harvest early for best flavor.'
  },
  {
    name: 'Swiss Chard',
    scientificName: 'Beta vulgaris',
    category: 'leafy',
    difficulty: 'easy',
    growthTime: 50,
    optimalPhMin: 6.0,
    optimalPhMax: 7.0,
    optimalTdsMin: 800,
    optimalTdsMax: 1200,
    optimalWaterTempMin: 16.0,
    optimalWaterTempMax: 20.0,
    optimalAirTempMin: 15.0,
    optimalAirTempMax: 25.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '10-12 hours daily, moderate intensity',
    description: 'Colorful stalks with nutritious leaves. Tolerant of various growing conditions.',
    image: 'https://example.com/swiss_chard.jpg',
    maintenanceLevel: 'low',
    notes: 'Harvest outer leaves regularly to promote new growth. Very productive plant.'
  },
  {
    name: 'Cilantro',
    scientificName: 'Coriandrum sativum',
    category: 'herb',
    difficulty: 'easy',
    growthTime: 35,
    optimalPhMin: 6.2,
    optimalPhMax: 6.8,
    optimalTdsMin: 400,
    optimalTdsMax: 800,
    optimalWaterTempMin: 15.0,
    optimalWaterTempMax: 18.0,
    optimalAirTempMin: 15.0,
    optimalAirTempMax: 22.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '8-10 hours daily, moderate intensity',
    description: 'Aromatic herb that prefers cooler temperatures. Bolt-sensitive, so harvest early.',
    image: 'https://example.com/cilantro.jpg',
    maintenanceLevel: 'low',
    notes: 'Bolts quickly in warm weather. Succession plant every 2-3 weeks.'
  },
  {
    name: 'Lemongrass',
    scientificName: 'Cymbopogon citratus',
    category: 'herb',
    difficulty: 'moderate',
    growthTime: 80,
    optimalPhMin: 5.5,
    optimalPhMax: 6.5,
    optimalTdsMin: 600,
    optimalTdsMax: 1000,
    optimalWaterTempMin: 18.0,
    optimalWaterTempMax: 22.0,
    optimalAirTempMin: 20.0,
    optimalAirTempMax: 28.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '10-12 hours daily, moderate intensity',
    description: 'Citrusy aromatic grass used in cooking. Drought-tolerant once established.',
    image: 'https://example.com/lemongrass.jpg',
    maintenanceLevel: 'medium',
    notes: 'Takes longer to establish but very hardy once growing. Cut from base for harvest.'
  },
  {
    name: 'Green Onion',
    scientificName: 'Allium cepa var. aggregatum',
    category: 'vegetable',
    difficulty: 'easy',
    growthTime: 30,
    optimalPhMin: 6.0,
    optimalPhMax: 7.0,
    optimalTdsMin: 400,
    optimalTdsMax: 800,
    optimalWaterTempMin: 16.0,
    optimalWaterTempMax: 20.0,
    optimalAirTempMin: 18.0,
    optimalAirTempMax: 25.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '10-12 hours daily, moderate intensity',
    description: 'Fast-growing and productive. Harvest by cutting above the root base for regrowth.',
    image: 'https://example.com/green_onion.jpg',
    maintenanceLevel: 'low',
    notes: 'Harvest outer leaves or cut above root base for regrowth. Very productive.'
  },
  {
    name: 'Bok Choy',
    scientificName: 'Brassica rapa',
    category: 'leafy',
    difficulty: 'moderate',
    growthTime: 35,
    optimalPhMin: 6.0,
    optimalPhMax: 7.0,
    optimalTdsMin: 600,
    optimalTdsMax: 1000,
    optimalWaterTempMin: 15.0,
    optimalWaterTempMax: 18.0,
    optimalAirTempMin: 15.0,
    optimalAirTempMax: 22.0,
    optimalHumidityMin: 40.0,
    optimalHumidityMax: 70.0,
    lightRequirements: '10-12 hours daily, moderate intensity',
    description: 'Asiatic green with nutritious leaves and stems. Prefers cooler temperatures.',
    image: 'https://example.com/bok_choy.jpg',
    maintenanceLevel: 'medium',
    notes: 'Prefers cooler conditions. Harvest by cutting base or individual leaves.'
  }
];

const seedPlants = async () => {
  try {
    console.log('🌱 Seeding plant profiles...');
    
    // Clear existing plant profiles
    await PlantProfile.destroy({ where: {} });
    
    // Create new plant profiles
    for (const plant of plantData) {
      await PlantProfile.create(plant);
      console.log(`✅ Added ${plant.name} to database`);
    }
    
    console.log(`\n🎉 Successfully seeded ${plantData.length} plant profiles!`);
  } catch (error) {
    console.error('❌ Error seeding plants:', error);
    throw error;
  }
};

module.exports = seedPlants;